### ISSUE TITLE
github.silent option was deprecated on Sep 25, 2023

### ISSUE THREAD

**Issue by sojinsamuel** [akhila-ariyachandra/akhilaariyachandra.com#241]
I am learning nextjs and find your repo. while studying it. i found the vercel.json file and the configuration inside it. After doing some research i found that Vercel team [released a new feature](https://vercel.com/changelog/disable-git-integration-comments) and github.silent has been deprecated.

For customisation or to have more granular control over disabling comments you can do the below to enable or disable :arrow_down:  

Visit _your-project/settings/git_

![Screenshot from 2023-10-06 23-25-57](https://github.com/akhila-ariyachandra/akhilaariyachandra.com/assets/77185816/b3674878-a865-40db-9b14-85f3560cb26e)

**Comment by akhila-ariyachandra** [comment]
Thanks for the heads up!!! I've removed the file and updated my project settings. #244

**Comment by sojinsamuel** [comment]
@akhila-ariyachandra I learned a lot from your repo. If that's possible can you provide me PR access to this repo. I made some update to the metadata config
