### ISSUE TITLE
Provide icon path in metadata config

### ISSUE THREAD

**Issue by sojinsamuel** [akhila-ariyachandra/akhilaariyachandra.com#247]
```javascript
export const metadata = {
  title: "Akhila Ariyachandra",
  description: "Web Developer",
  // Provide icon path
  icons: {
    icon: "/icon.png",
  },
  metadataBase: new URL("https://akhilaariyachandra.com"),
  ...
  ...
 }
```
This will add additional type of website icon in head’s meta tags. If you will do both, that will help you supporting older browsers, including those that don’t support SVG favicons.

#### Readings
- [Metadata API Icons Media Attribute Type](https://github.com/vercel/next.js/issues/45859)
- [Adding Favicon to NextJs 13 Beta](https://stackoverflow.com/questions/75674866/adding-favicon-to-nextjs-13-beta-no-pages-folder)

P.S. If its possible can i get PR access to this or your any other repos. I am learning something new everyday from your codebase and it helps me a lot in exploring and putting things into practice. Thanks in advance

**Comment by akhila-ariyachandra** [comment]
The icon URL is automatically added by the `icon.png` file.

Sorry, I can't give PR access to any of my repos unless there is a very good reason for it. Feel free to fork the repo if you want to try out changes for it.
